name: Maven Package and Deploy

on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: 设置 JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: 构建 Maven 项目
        run: mvn -B package --file pom.xml

      - name: 复制 Jar 文件
        run: cp /home/runner/work/Actions/Actions/target/Actions-1.1.3-sources.jar ./Actions-1.1.3.jar

      - name: Build Docker Image
        run: |
          docker build -t mrsxs/jar:1.1.1 .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push mrsxs/jar:1.1.1

      - name: 部署 Docker 镜像
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull mrsxs/jar/actios:1.1.1
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 8080:8080 mrsxs/jar/actios:1.1.1
